name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['monarx-events', 'phishing-detector']
    steps:
      - uses: actions/checkout@v4
      - name: Detect environment
        working-directory: container/${{matrix.image}}
        id: projectEnv
        run: |
          RUNTIME=""
          HAS_TESTS="false"
          if [ -f "go.mod" ]; then
            RUNTIME="go"
          fi
          if grep -q -E '^test:' Makefile; then
            HAS_TESTS="true"
          fi
          echo $RUNTIME
          echo $HAS_TESTS
          echo "runtime=${RUNTIME}" >> $GITHUB_OUTPUT
          echo "hasTests=${HAS_TESTS}" >> $GITHUB_OUTPUT
      - name: Debug Outputs
        run: |
          echo "Runtime is: ${{ steps.projectEnv.outputs.runtime }}"
          echo "Has tests: ${{ steps.projectEnv.outputs.hasTests }}"
      - name: Setup Go
        if: ${{ (steps.projectEnv.outputs.runtime == 'go') && (steps.projectEnv.outputs.hasTests == 'true') }}
        uses: actions/setup-go@v5
        with:
          go-version-file: "container/${{matrix.image}}/go.mod"

      - name: Run tests
        working-directory: container/${{matrix.image}}
        if: ${{steps.projectEnv.outputs.hasTests != 'false'}}
        run: |
          make test
