name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect environment
        working-directory: container/monarx-events
        id: projectEnv
        run: |
          RUNTIME=""
          HAS_TESTS="false"
          if [ -f "go.mod" ]; then
            RUNTIME="go"
          fi
          if grep -q -E '^test:' Makefile; then
            HAS_TESTS="true"
          fi
          echo $RUNTIME
          echo $HAS_TESTS
          echo "runtime=$RUNTIME" >> $GITHUB_OUTPUT
          echo "hasTests=$HAS_TESTS" >> $GITHUB_OUTPUT

      - name: Setup Go
        if: ${{ needs.projectEnv.outputs.runtime == 'go' && needs.projectEnv.outputs.hasTests == 'true' }}
        uses: actions/setup-go@v5
        with:
          go-version-file: 'container/monarx-events/go.mod'

      - name: Run tests
        working-directory: container/monarx-events
        if: ${{needs.projectEnv.outputs.hasTests != 'false'}}
        run: |
          make test
